name: tndwolf_ecs
description: ECS Framework for my projects.
version: 0.1.0
#author: Luca Carbone <tndwolf@gmail.com>
#homepage: https://www.tndwolf.org

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0'
